persistence:
  postgresql:
    secretRef:
      name: backstage-psql-secret-developer-hub
      userKey: POSTGRES_USER
      passwordKey: POSTGRES_PASSWORD
    serviceRef:
      name: backstage-psql-developer-hub
      port: 5432
      databaseName: backstage_plugin_orchestrator
      databaseSchema: create-ocp-namespace-swt
image:
  repository: ghcr.io/evanshortiss/create-ocp-namespace-swt
  tag: 0.1.5
# Environment variables for the workflow
env:
  backstageBackendUrl: ""
  backstageBackendBearerToken: ""
  gitlabUrl: ""
  gitlabToken: ""
  swtRef: "template:default/orchestrator-namespace-request"
backstage:
  softwareTemplateNamespace:
